# Generated by Django 4.0.3 on 2022-03-12 11:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Auditor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('places', models.PositiveIntegerField(default=0)),
                ('microphones', models.BooleanField(default=False)),
                ('speakers', models.BooleanField(default=False)),
                ('computers', models.PositiveIntegerField(default=0)),
                ('proektor', models.BooleanField(default=False)),
                ('interactiveBoard', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Corpus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Bron',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('allowed', models.BooleanField(default=False)),
                ('start_time', models.PositiveSmallIntegerField()),
                ('end_time', models.PositiveSmallIntegerField()),
                ('comment', models.TextField(blank=True, max_length=50)),
                ('auditor', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='app.auditor')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
        migrations.AddField(
            model_name='auditor',
            name='corpus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.corpus'),
        ),
    ]
