# Generated by Django 4.0.3 on 2022-03-12 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditor',
            name='tables',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
