# Generated by Django 4.0.3 on 2022-03-13 03:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auditor_tables'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auditor',
            options={'verbose_name': 'Аудитория', 'verbose_name_plural': 'Аудитории'},
        ),
        migrations.AlterModelOptions(
            name='bron',
            options={'verbose_name': 'Заявка', 'verbose_name_plural': 'Заявки'},
        ),
        migrations.AlterModelOptions(
            name='corpus',
            options={'verbose_name': 'Копрус', 'verbose_name_plural': 'Корпуса'},
        ),
        migrations.AddField(
            model_name='auditor',
            name='user',
            field=models.CharField(blank=True, max_length=50, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='auditor',
            name='computers',
            field=models.PositiveIntegerField(default=0, verbose_name='Компьютеры'),
        ),
        migrations.AlterField(
            model_name='auditor',
            name='corpus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.corpus', verbose_name='Корпус'),
        ),
        migrations.AlterField(
            model_name='auditor',
            name='interactiveBoard',
            field=models.BooleanField(default=False, verbose_name='Интер. доска'),
        ),
        migrations.AlterField(
            model_name='auditor',
            name='microphones',
            field=models.BooleanField(default=False, verbose_name='Микрофон'),
        ),
        migrations.AlterField(
            model_name='auditor',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Номер'),
        ),
        migrations.AlterField(
            model_name='auditor',
            name='places',
            field=models.PositiveIntegerField(default=0, verbose_name='Мест'),
        ),
        migrations.AlterField(
            model_name='auditor',
            name='proektor',
            field=models.BooleanField(default=False, verbose_name='Проектор'),
        ),
        migrations.AlterField(
            model_name='auditor',
            name='speakers',
            field=models.BooleanField(default=False, verbose_name='Колонки'),
        ),
        migrations.AlterField(
            model_name='auditor',
            name='tables',
            field=models.PositiveIntegerField(default=0, verbose_name='Столов'),
        ),
        migrations.AlterField(
            model_name='bron',
            name='allowed',
            field=models.BooleanField(default=False, verbose_name='Одобрена'),
        ),
        migrations.AlterField(
            model_name='bron',
            name='auditor',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='app.auditor', verbose_name='Аудитория'),
        ),
        migrations.AlterField(
            model_name='bron',
            name='comment',
            field=models.TextField(blank=True, max_length=50, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='bron',
            name='date',
            field=models.DateField(verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='bron',
            name='end_time',
            field=models.PositiveSmallIntegerField(verbose_name='конец'),
        ),
        migrations.AlterField(
            model_name='bron',
            name='start_time',
            field=models.PositiveSmallIntegerField(verbose_name='начало'),
        ),
        migrations.AlterField(
            model_name='bron',
            name='user',
            field=models.CharField(max_length=50, verbose_name='Пользователь'),
        ),
    ]
