# Generated by Django 4.0.3 on 2022-03-13 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_auditor_options_alter_bron_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bron',
            name='user',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Пользователь'),
        ),
    ]
